package api

const (
	RESOURCE_LOGIN              = "login"
	RESOURCE_MEALS              = "meals"
	RESOURCE_MEALSINDAY         = "mealsinday"
	RESOURCE_PRODUCTS           = "products"
	RESOURCE_LOOSEPRODUCTSINDAY = "looseproductsinday"
	RESOURCE_CATEGORIES         = "categories"
	RESOURCE_OPTIMIZEMEAL       = "optimizemeal"
)

const (
	PATH_LOGIN = RESOURCE_LOGIN

	PATH_MEALS         = "/" + RESOURCE_MEALS
	PATH_MEALS_WITH_ID = "/" + RESOURCE_MEALS + "/:id"

	PATH_MEALSINDAY         = "/" + RESOURCE_MEALSINDAY
	PATH_MEALSINDAY_WITH_ID = "/" + RESOURCE_MEALSINDAY + "/:id"

	PATH_PRODUCTS         = "/" + RESOURCE_PRODUCTS
	PATH_PRODUCTS_WITH_ID = "/" + RESOURCE_PRODUCTS + "/:id"

	PATH_LOOSEPRODUCTSINDAY         = "/" + RESOURCE_LOOSEPRODUCTSINDAY
	PATH_LOOSEPRODUCTSINDAY_WITH_ID = "/" + RESOURCE_LOOSEPRODUCTSINDAY + "/:id"

	PATH_CATEGORIES         = "/" + RESOURCE_CATEGORIES
	PATH_CATEGORIES_WITH_ID = "/" + RESOURCE_CATEGORIES + "/:id"

	PATH_OPTIMIZEMEAL         = "/" + RESOURCE_OPTIMIZEMEAL
	PATH_OPTIMIZEMEAL_WITH_ID = "/" + RESOURCE_OPTIMIZEMEAL + "/:id"
)
